### ISSUE TITLE
style: format optimization

### ISSUE THREAD

**Issue by ArchiDog1998** [shichuyibushishiwu/Tuna.Revit.Extensions#25]
Hi, I saw the flag enum here with decimal. This is okay for smaller numbers, but it is hard to read when the number is large.

https://github.com/shichuyibushishiwu/Tuna.Revit.Extensions/blob/8b00f72612634630bc5b7dd54182af0e9b6b4e14/src/Data/Availability.cs#L19-L54

What I recommend is to write it with [`<<`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#left-shift-operator-).

``` c#
/// <summary>
/// Invalid
/// </summary>
[Flags]
public enum AvailabilityMode : byte
{
    /// <summary>
    /// 
    /// </summary>
    Always = 0,

    /// <summary>
    /// 
    /// </summary>
    OnlyDocument = 1 << 0,

    /// <summary>
    /// 
    /// </summary>
    OnlyFamily = 1 << 1,

    /// <summary>
    /// 
    /// </summary>
    OnlyProject = 1 << 2,

    /// <summary>
    /// 
    /// </summary>
    OnlyThreeDView = 1 << 3,

    /// <summary>
    /// 
    /// </summary>
    OnlyPlanView = 1 << 4,
}
```

**Comment by shichuyibushishiwu** [comment]
That's great!  btw, this feature has been removed from develop branch.

**Comment by ArchiDog1998** [comment]
Oh, I am sorry to hear that. Thanks for your reply!
