### ISSUE TITLE
panel.AddPushButton<Commands.MyCommand>()缺配置

### ISSUE THREAD

**Issue by CY-design** [shichuyibushishiwu/Tuna.Revit.Extensions#49]
![image](https://github.com/shichuyibushishiwu/Tuna.Revit.Extensions/assets/34803977/01a51753-c031-4e86-8446-18d73caee923)
`panel.AddPushButton<Commands.MyCommand>();`
缺少通过回调进行配置，能否用IRibbonButtonData，这样就可以在入口处进行Name，LargeImage(方便使用图片地址)等的配置，Revit原生的PulldownButton的LargeImage不能使用String作为入口，配置比较麻烦。

**Comment by shichuyibushishiwu** [comment]
已经添加到dev 分支，可以拉取测试一下具体的功能

**Comment by CY-design** [comment]
![image](https://github.com/shichuyibushishiwu/Tuna.Revit.Extensions/assets/34803977/ad5786ec-549c-47ec-b814-f6306adcbe68)
很好
